import type { Metadata } from 'next'
import './globals.css'
import { geistMono, geistSans } from '@/config'

export const metadata: Metadata = {
  title: 'Teslo | Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-geist-sans antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
